const nodemailer = require('nodemailer');
const DemoRequest = require('../models/DemoRequest');

/**
 * Helper to send email notification
 */
const sendDemoRequestEmail = async (demoData) => {
  const recipientEmail = process.env.EMAIL_TO || 'orangevirtualconnect@gmail.com';
  const smtpUser = process.env.SMTP_USER;
  const smtpPass = process.env.SMTP_PASS;

  const htmlContent = `
    <div style="font-family: 'Segoe UI', Arial, sans-serif; max-width: 600px; margin: 0 auto; border: 1px solid #e0e0e0; border-radius: 12px; overflow: hidden; background-color: #ffffff;">
      <div style="background: linear-gradient(135deg, #FF8A00 0%, #FF6A00 100%); padding: 24px 30px; text-color: #ffffff;">
        <h2 style="color: #ffffff; margin: 0; font-size: 22px; font-weight: 800; tracking-tight: -0.5px;">
          🚀 New Enterprise Demo Request
        </h2>
        <p style="color: #fff3eb; margin: 6px 0 0 0; font-size: 14px;">
          Medora360 Hospital Management System
        </p>
      </div>

      <div style="padding: 28px 30px;">
        <p style="color: #333333; font-size: 15px; margin-top: 0;">
          A new demo request has been submitted from the website landing page.
        </p>

        <table style="width: 100%; border-collapse: collapse; margin-top: 20px; font-size: 14px;">
          <tbody>
            <tr>
              <td style="padding: 12px 16px; font-weight: bold; color: #555555; background-color: #f9fafb; border-bottom: 1px solid #eeeeee; width: 35%;">Full Name</td>
              <td style="padding: 12px 16px; color: #111111; font-weight: 600; border-bottom: 1px solid #eeeeee;">${demoData.name}</td>
            </tr>
            <tr>
              <td style="padding: 12px 16px; font-weight: bold; color: #555555; background-color: #f9fafb; border-bottom: 1px solid #eeeeee;">Hospital / Facility</td>
              <td style="padding: 12px 16px; color: #111111; font-weight: 600; border-bottom: 1px solid #eeeeee;">${demoData.hospital}</td>
            </tr>
            <tr>
              <td style="padding: 12px 16px; font-weight: bold; color: #555555; background-color: #f9fafb; border-bottom: 1px solid #eeeeee;">Phone Number</td>
              <td style="padding: 12px 16px; color: #FF6A00; font-weight: bold; border-bottom: 1px solid #eeeeee;">
                <a href="tel:${demoData.phone}" style="color: #FF6A00; text-decoration: none;">${demoData.phone}</a>
              </td>
            </tr>
            <tr>
              <td style="padding: 12px 16px; font-weight: bold; color: #555555; background-color: #f9fafb; border-bottom: 1px solid #eeeeee;">Work Email</td>
              <td style="padding: 12px 16px; color: #111111; border-bottom: 1px solid #eeeeee;">
                <a href="mailto:${demoData.email}" style="color: #2563eb; text-decoration: none;">${demoData.email}</a>
              </td>
            </tr>
            <tr>
              <td style="padding: 12px 16px; font-weight: bold; color: #555555; background-color: #f9fafb; border-bottom: 1px solid #eeeeee; vertical-align: top;">Message / Notes</td>
              <td style="padding: 12px 16px; color: #333333; border-bottom: 1px solid #eeeeee; white-space: pre-line;">${demoData.message || 'No additional notes provided.'}</td>
            </tr>
            <tr>
              <td style="padding: 12px 16px; font-weight: bold; color: #555555; background-color: #f9fafb;">Submitted At</td>
              <td style="padding: 12px 16px; color: #666666;">${new Date().toLocaleString('en-US', { timeZone: 'Asia/Kolkata' })} (IST)</td>
            </tr>
          </tbody>
        </table>

        <div style="margin-top: 30px; text-align: center;">
          <a href="mailto:${demoData.email}?subject=Medora360%20Demo%20Follow-up%20for%20${encodeURIComponent(demoData.hospital)}" 
             style="display: inline-block; background: #FF6A00; color: #ffffff; text-decoration: none; padding: 12px 28px; font-weight: bold; border-radius: 8px; font-size: 14px;">
            Reply to ${demoData.name}
          </a>
        </div>
      </div>

      <div style="background-color: #f4f5f7; padding: 16px 30px; text-align: center; font-size: 12px; color: #888888;">
        This automated notification was generated by Medora360 Website.
      </div>
    </div>
  `;

  if (!smtpUser || !smtpPass) {
    console.log('---------------------------------------------------------');
    console.log('[DEMO REQUEST EMAIL NOTIFICATION - SMTP CREDENTIALS NOT SET]');
    console.log(`To: ${recipientEmail}`);
    console.log(`Name: ${demoData.name}`);
    console.log(`Hospital: ${demoData.hospital}`);
    console.log(`Phone: ${demoData.phone}`);
    console.log(`Email: ${demoData.email}`);
    console.log(`Message: ${demoData.message}`);
    console.log('Set SMTP_USER and SMTP_PASS in backend/.env to send live emails via SMTP.');
    console.log('---------------------------------------------------------');
    return { sent: false, reason: 'SMTP credentials not configured in .env' };
  }

  const transporter = nodemailer.createTransport({
    host: process.env.SMTP_HOST || 'smtp.gmail.com',
    port: parseInt(process.env.SMTP_PORT || '587'),
    secure: process.env.SMTP_SECURE === 'true', // true for 465, false for 587
    auth: {
      user: smtpUser,
      pass: smtpPass
    }
  });

  const mailOptions = {
    from: `"Medora360 Demo Request" <${smtpUser}>`,
    to: recipientEmail,
    replyTo: demoData.email,
    subject: `🚀 Demo Request: ${demoData.hospital} (${demoData.name})`,
    html: htmlContent
  };

  await transporter.sendMail(mailOptions);
  return { sent: true };
};

// @desc    Submit a new demo request
// @route   POST /api/demo-request
// @access  Public
const createDemoRequest = async (req, res) => {
  try {
    const { name, hospital, phone, email, message } = req.body;

    if (!name || !hospital || !phone || !email) {
      return res.status(400).json({
        success: false,
        message: 'Please provide all required fields (Name, Hospital, Phone, Email)'
      });
    }

    const demoRequest = await DemoRequest.create({
      name,
      hospital,
      phone,
      email,
      message: message || ''
    });

    let emailSent = false;
    let emailError = null;

    try {
      const emailResult = await sendDemoRequestEmail({ name, hospital, phone, email, message });
      emailSent = emailResult.sent;
      if (!emailResult.sent && emailResult.reason) {
        emailError = emailResult.reason;
      }
    } catch (err) {
      console.error('Failed to send email notification:', err);
      emailSent = false;
      emailError = err.message;
    }

    demoRequest.emailSent = emailSent;
    demoRequest.emailError = emailError;
    await demoRequest.save();

    res.status(201).json({
      success: true,
      message: 'Demo request submitted successfully',
      data: demoRequest
    });

  } catch (error) {
    console.error('Error handling demo request:', error);
    res.status(500).json({
      success: false,
      message: 'Server error while submitting demo request',
      error: error.message
    });
  }
};

// @desc    Get all demo requests (for Super Admin / Admin)
// @route   GET /api/demo-request
// @access  Private
const getDemoRequests = async (req, res) => {
  try {
    const requests = await DemoRequest.find().sort({ createdAt: -1 });
    res.json({
      success: true,
      count: requests.length,
      data: requests
    });
  } catch (error) {
    res.status(500).json({
      success: false,
      message: 'Error fetching demo requests',
      error: error.message
    });
  }
};

module.exports = {
  createDemoRequest,
  getDemoRequests
};
