const express = require('express');
const router = express.Router();
const m3WebhookController = require('../controllers/m3WebhookController');

// ==========================================
// M3 Webhook Health Check
// ==========================================
router.get('/health', (req, res) => {
    res.status(200).json({
        status: 'OK',
        module: 'ABDM-M3-HIU',
        timestamp: new Date().toISOString()
    });
});

// ==========================================
// 1. Consent Request On-Init Callback
// Receives the consent request ID generated by Gateway
// Gateway Endpoint: /v3/hiu/consent/request/on-init
// ==========================================
router.post('/v3/hiu/consent/request/on-init', m3WebhookController.handleConsentOnInit);
router.post('/api/v3/hiu/consent/request/on-init', m3WebhookController.handleConsentOnInit);

// ==========================================
// 2. Consent Request On-Status Callback
// Receives status polling responses
// Gateway Endpoint: /v3/hiu/consent/request/on-status
// ==========================================
router.post('/v3/hiu/consent/request/on-status', m3WebhookController.handleConsentOnStatus);
router.post('/api/v3/hiu/consent/request/on-status', m3WebhookController.handleConsentOnStatus);

// ==========================================
// 3. Consent Request Notification Callback (Notify)
// Receives notification when a patient grants/denies/revokes consent
// Gateway Endpoint: /v3/hiu/consent/request/notify (and variations)
// ==========================================
router.post('/v3/hiu/consent/request/notify', m3WebhookController.handleConsentNotify);
router.post('/api/v3/hiu/consent/request/notify', m3WebhookController.handleConsentNotify);
router.post('/v3/hiu/consent/request/hiu/notify', m3WebhookController.handleConsentNotify);
router.post('/api/v3/hiu/consent/request/hiu/notify', m3WebhookController.handleConsentNotify);

// ==========================================
// 4. Consent Artefact On-Fetch Callback
// Receives the actual signed consent artefact
// Gateway Endpoint: /v3/hiu/consent/on-fetch
// ==========================================
router.post('/v3/hiu/consent/on-fetch', m3WebhookController.handleConsentOnFetch);
router.post('/api/v3/hiu/consent/on-fetch', m3WebhookController.handleConsentOnFetch);

// ==========================================
// 5. Health Information On-Request Callback
// Receives acknowledgment of health data request
// Gateway Endpoint: /v3/hiu/health-information/on-request
// ==========================================
router.post('/v3/hiu/health-information/on-request', m3WebhookController.handleHealthInformationOnRequest);
router.post('/api/v3/hiu/health-information/on-request', m3WebhookController.handleHealthInformationOnRequest);
router.post('/v3/health-information/hiu/on-request', m3WebhookController.handleHealthInformationOnRequest);
router.post('/api/v3/health-information/hiu/on-request', m3WebhookController.handleHealthInformationOnRequest);

// ==========================================
// 6. Data Push URL Receiver
// Endpoint where HIPs push encrypted FHIR bundles to HIU
// Endpoint: /v3/data/push
// ==========================================
router.post('/v3/data/push', m3WebhookController.handleDataPush);
router.post('/api/v3/data/push', m3WebhookController.handleDataPush);
router.post('/data/push', m3WebhookController.handleDataPush);

// ==========================================
// Internal / Medora360 Doctor Portal APIs
// ==========================================
// Initiate a consent request outbound call to ABDM Gateway
router.post('/consent/request/init', m3WebhookController.triggerInitiateConsentRequest);
router.post('/consent/request/status', m3WebhookController.triggerGetConsentStatus);
router.get('/consent/request/status/:consentRequestId', m3WebhookController.triggerGetConsentStatus);
router.get('/consent/states', m3WebhookController.getConsentStatesHandler);
router.post('/consent/artefact/fetch', m3WebhookController.triggerFetchConsentArtefact);
router.get('/consent/artefacts', m3WebhookController.getConsentArtefactsHandler);

// Trigger health data request outbound call to ABDM Gateway (Step 3)
router.post('/data/request/init', m3WebhookController.triggerInitiateDataRequest);
router.get('/data/keys', m3WebhookController.getKeyMaterialsHandler);
router.get('/data/records', m3WebhookController.getDecryptedRecordsHandler);

module.exports = router;
