const mongoose = require('mongoose');
const Symptom = require('../models/Symptom');
require('dotenv').config({ path: require('path').join(__dirname, '../.env') });

const symptoms = [
  'Fever',
  'Chills',
  'Fatigue',
  'Weakness',
  'Bodyache',
  'Sweating',
  'Weight loss',
  'Weight gain',
  'Dehydration',
  'Loss appetite',
  'Irritability',
  'Drowsiness',
  'Insomnia',
  'Restlessness',
  'Cough',
  'Dry cough',
  'Wet cough',
  'Breathlessness',
  'Wheezing',
  'Sneezing',
  'Running nose',
  'Blocked nose',
  'Sore throat',
  'Hoarseness',
  'Chest pain',
  'Phlegm',
  'Hemoptysis',
  'Snoring',
  'Earache',
  'Tinnitus',
  'Hearing loss',
  'Vertigo',
  'Nasal bleeding',
  'Sinus pain',
  'Toothache',
  'Gum bleeding',
  'Mouth ulcer',
  'Bad breath',
  'Acidity',
  'Heartburn',
  'Nausea',
  'Vomiting',
  'Bloating',
  'Constipation',
  'Diarrhea',
  'Dysentery',
  'Abdominal pain',
  'Indigestion',
  'Flatulence',
  'Burping',
  'Jaundice',
  'Blood in stool',
  'Black stool',
  'Rectal pain',
  'Appetite increase',
  'Palpitations',
  'Chest tightness',
  'Hypertension',
  'Hypotension',
  'Fainting',
  'Edema',
  'Cyanosis',
  'Headache',
  'Migraine',
  'Dizziness',
  'Tremors',
  'Seizures',
  'Numbness',
  'Tingling',
  'Paralysis',
  'Memory loss',
  'Confusion',
  'Speech difficulty',
  'Imbalance',
  'Syncope',
  'Backpain',
  'Neck pain',
  'Jointpain',
  'Knee pain',
  'Muscle pain',
  'Stiffness',
  'Swelling',
  'Cramps',
  'Fracture pain',
  'Limping',
  'Rash',
  'Itching',
  'Dry skin',
  'Redness',
  'Pigmentation',
  'Acne',
  'Boils',
  'Blisters',
  'Bruising',
  'Hairfall',
  'Dandruff',
  'Skin peeling',
  'Hives',
  'Redeye',
  'Watering eyes',
  'Blurred vision',
  'Double vision',
  'Eye pain',
  'Eye discharge',
  'Photophobia',
  'Vision loss',
  'Burning urination',
  'Frequent urination',
  'Bloodinurine',
  'Urgency',
  'Incontinence',
  'Flankpain',
  'Reducedurine',
  'Retention',
  'Irregularperiods',
  'Heavybleeding',
  'Missedperiods',
  'Vaginaldischarge',
  'Pelvicpain',
  'Infertility',
  'Menstrualcramps',
  'Breastpain',
  'Anxiety',
  'Depression',
  'Stress',
  'Panic',
  'Hallucinations',
  'Moodswings',
  'Aggression',
  'Hyperactivity',
  'Sugarcraving',
  'Slowhealing',
  'Pus discharge',
  'Swollen lymphnodes',
  'Crying',
  'Poor feeding',
  'Irritation',
  'Teething pain',
  'Colic',
  'Unconsciousness',
  'Breath failure',
  'Severe bleeding',
  'Cardiac arrest',
  'Shock'
];

const seedSymptoms = async () => {
  try {
    // Connect to MongoDB using env variable
    await mongoose.connect(process.env.MONGO_URI);

    console.log('Seeding symptoms to database...');

    // Clear existing symptoms
    await Symptom.deleteMany({});

    // Insert all symptoms
    const symptomDocs = symptoms.map(name => ({ name: name.toLowerCase() }));
    await Symptom.insertMany(symptomDocs);

    console.log(`✓ Successfully seeded ${symptoms.length} symptoms to database`);
    process.exit(0);
  } catch (error) {
    console.error('Seeding error:', error);
    process.exit(1);
  }
};

seedSymptoms();
